### ISSUE TITLE
run-debug changes directory when run as admin

### ISSUE THREAD

**Issue by Tashaa78** [mixerp/init#2]
run-debug.bat file wont run without admin permissions on some machine. When you run a batch file as administrator under windows 10 the current directory gets set to C:\windows\system32. This prevents the scripts from working correctly if you use relative paths.

`SET currentDirectory=%~dp0` couldn't do the work. 

 Included the two lines of code below for it to work.

`@setlocal enableextensions`
`@cd /d "%~dp0" `

**Comment by mixerp** [comment]
Tashaa78, thank you for pointing out. Could you please test, validate, and send a pull request regarding this issue? 👍

**Comment by Tashaa78** [comment]
Sure, will do that.
